# ABSTRACT AND INTRODUCTION

Here, I use Python 3.10 and visualizing software PowerBI to create a overview of financial relationship between medical manufactors and hospital - specifically Moffit Cancer Center. The data is open source gather from OpenPaymentData.cms.gov

Open payments is a public platform containing metadata showcasing the financial relationship between heathcare provides and its steak holders - medical companies, patients, goverment. I have always curious about the fundings acquisition and expense - where it cocme from, how it's used, what role each steak holders play in the financial envadors. Hence, i am using the data from a pretigious teaching hospital - Moffitt Cancer Center - to explore its payment in 2024.

# GOALS AND OBJECTIVES

1. Total annual investment
2. Properties of Nature of payment
3. Top 10 company made research payment to Moffitt
2. Top and least funded product type
3. Top and least funded specialty 
4. Seasonal trend in spending

# RAW DATA

In [10]:
import pandas as pd
import numpy as np
import os

In [11]:
research_pay = pd.read_csv("RAW_Research_payment.csv")
research_pay

,Change_Type,Covered_Recipient_Type,Noncovered_Recipient_Entity_Name,Teaching_Hospital_CCN,Teaching_Hospital_ID,Teaching_Hospital_Name,Covered_Recipient_Profile_ID,Covered_Recipient_NPI,Covered_Recipient_First_Name,Covered_Recipient_Middle_Name,...,Preclinical_Research_Indicator,Delay_in_Publication_Indicator,Name_of_Study,Dispute_Status_for_Publication,Record_ID,Program_Year,Payment_Publication_Date,ClinicalTrials_Gov_Identifier,Research_Information_Link,Context_of_Research
0,NEW,Covered Recipient Teaching Hospital,NaN,100271,14408,Moffitt Cancer Center,NaN,NaN,NaN,NaN,...,No,No,"Symphony-1: A Phase 1b/3 Double-Blind, Randomi...",No,1071108326,2024,06/30/2025,NCT04224493,NaN,NaN
1,NEW,Covered Recipient Teaching Hospital,NaN,100271,14408,Moffitt Cancer Center,NaN,NaN,NaN,NaN,...,No,No,"Symphony-1: A Phase 1b/3 Double-Blind, Randomi...",No,1071108328,2024,06/30/2025,NCT04224493,NaN,NaN
2,NEW,Covered Recipient Teaching Hospital,NaN,100271,14408,Moffitt Cancer Center,NaN,NaN,NaN,NaN,...,No,No,"Symphony-1: A Phase 1b/3 Double-Blind, Randomi...",No,1071104134,2024,06/30/2025,NCT04224493,NaN,NaN
3,NEW,Covered Recipient Teaching Hospital,NaN,100271,14408,Moffitt Cancer Center,NaN,NaN,NaN,NaN,...,No,No,"Symphony-1: A Phase 1b/3 Double-Blind, Randomi...",No,1071104136,2024,06/30/2025,NCT04224493,NaN,NaN
4,NEW,Covered Recipient Teaching Hospital,NaN,100271,14408,Moffitt Cancer Center,NaN,NaN,NaN,NaN,...,No,No,"Symphony-1: A Phase 1b/3 Double-Blind, Randomi...",No,1071108476,2024,06/30/2025,NCT04224493,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2298,NEW,Covered Recipient Teaching Hospital,NaN,100271,14408,Moffitt Cancer Center,NaN,NaN,NaN,NaN,...,No,No,A single Arm Phase 1b study of hyper-CVAD plus...,No,1153015173,2024,06/30/2025,NaN,NaN,NaN
2299,NEW,Covered Recipient Teaching Hospital,NaN,100271,14408,Moffitt Cancer Center,NaN,NaN,NaN,NaN,...,No,No,A single Arm Phase 1b study of hyper-CVAD plus...,No,1153015175,2024,06/30/2025,NaN,NaN,NaN
2300,NEW,Covered Recipient Teaching Hospital,NaN,100271,14408,Moffitt Cancer Center,NaN,NaN,NaN,NaN,...,No,No,A single Arm Phase 1b study of hyper-CVAD plus...,No,1153015177,2024,06/30/2025,NaN,NaN,NaN
2301,NEW,Covered Recipient Teaching Hospital,NaN,100271,14408,Moffitt Cancer Center,NaN,NaN,NaN,NaN,...,No,No,A single Arm Phase 1b study of hyper-CVAD plus...,No,1153015179,2024,06/30/2025,NaN,NaN,NaN
2302,NEW,Covered Recipient Teaching Hospital,NaN,100271,14408,Moffitt Cancer Center,NaN,NaN,NaN,NaN,...,No,No,A single Arm Phase 1b study of hyper-CVAD plus...,No,1153015181,2024,06/30/2025,NaN,NaN,NaN

# DATA CLEAN UP

## Strip and remove empty columns

In [17]:
def strip_n_drop_raw_data(df):
    # Drop columns contain all NaN. Now there are only 89 cols from the original 252 cols. A significant decreased!
    print(f"Shape before: {df.shape}")
    df = df.dropna(axis="columns", how="all")

    for col in df.columns:
        if df[col].dtype == "object":
            df[col] = df[col].str.lower()
            df[col] = df[col].str.strip(".!? \n\t")

    print(f"Shape after: {df.shape}")
    return df

research_pay_clean = strip_n_drop_raw_data(research_pay)
research_pay_clean

Shape before: (2303, 252)
Shape after: (2303, 89)

C:\Users\delta\AppData\Local\Temp\ipykernel_27920\3369786926.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].str.lower()
C:\Users\delta\AppData\Local\Temp\ipykernel_27920\3369786926.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].str.strip(".!? \n\t")

,Change_Type,Covered_Recipient_Type,Teaching_Hospital_CCN,Teaching_Hospital_ID,Teaching_Hospital_Name,Recipient_Primary_Business_Street_Address_Line1,Recipient_Primary_Business_Street_Address_Line2,Recipient_City,Recipient_State,Recipient_Zip_Code,...,Preclinical_Research_Indicator,Delay_in_Publication_Indicator,Name_of_Study,Dispute_Status_for_Publication,Record_ID,Program_Year,Payment_Publication_Date,ClinicalTrials_Gov_Identifier,Research_Information_Link,Context_of_Research
0,new,covered recipient teaching hospital,100271,14408,moffitt cancer center,12902 magnolia dr,NaN,tampa,fl,33612,...,no,no,"symphony-1: a phase 1b/3 double-blind, randomi...",no,1071108326,2024,06/30/2025,nct04224493,NaN,NaN
1,new,covered recipient teaching hospital,100271,14408,moffitt cancer center,12902 magnolia dr,NaN,tampa,fl,33612,...,no,no,"symphony-1: a phase 1b/3 double-blind, randomi...",no,1071108328,2024,06/30/2025,nct04224493,NaN,NaN
2,new,covered recipient teaching hospital,100271,14408,moffitt cancer center,12902 magnolia dr,NaN,tampa,fl,33612,...,no,no,"symphony-1: a phase 1b/3 double-blind, randomi...",no,1071104134,2024,06/30/2025,nct04224493,NaN,NaN
3,new,covered recipient teaching hospital,100271,14408,moffitt cancer center,12902 magnolia dr,NaN,tampa,fl,33612,...,no,no,"symphony-1: a phase 1b/3 double-blind, randomi...",no,1071104136,2024,06/30/2025,nct04224493,NaN,NaN
4,new,covered recipient teaching hospital,100271,14408,moffitt cancer center,12902 magnolia dr,NaN,tampa,fl,33612,...,no,no,"symphony-1: a phase 1b/3 double-blind, randomi...",no,1071108476,2024,06/30/2025,nct04224493,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2298,new,covered recipient teaching hospital,100271,14408,moffitt cancer center,12902 magnolia dr,NaN,tampa,fl,33612,...,no,no,a single arm phase 1b study of hyper-cvad plus...,no,1153015173,2024,06/30/2025,NaN,NaN,NaN
2299,new,covered recipient teaching hospital,100271,14408,moffitt cancer center,12902 magnolia dr,NaN,tampa,fl,33612,...,no,no,a single arm phase 1b study of hyper-cvad plus...,no,1153015175,2024,06/30/2025,NaN,NaN,NaN
2300,new,covered recipient teaching hospital,100271,14408,moffitt cancer center,12902 magnolia dr,NaN,tampa,fl,33612,...,no,no,a single arm phase 1b study of hyper-cvad plus...,no,1153015177,2024,06/30/2025,NaN,NaN,NaN
2301,new,covered recipient teaching hospital,100271,14408,moffitt cancer center,12902 magnolia dr,NaN,tampa,fl,33612,...,no,no,a single arm phase 1b study of hyper-cvad plus...,no,1153015179,2024,06/30/2025,NaN,NaN,NaN
2302,new,covered recipient teaching hospital,100271,14408,moffitt cancer center,12902 magnolia dr,NaN,tampa,fl,33612,...,no,no,a single arm phase 1b study of hyper-cvad plus...,no,1153015181,2024,06/30/2025,NaN,NaN,NaN

## Extract infomation of Hospital (recipients), Publications, Principal investigators, Donors

### Group the columns into small chunk for managable cleanup in bulk

In [18]:
# For easy managment reduce the numuber of columns slowly
# Use the code below to gate out infomation about Moffit, as there should only be 1 hospital, 2 adress associate with Moffitt from quick web search
def large_df_to_smaller_groups(big_df):
    # Moffit info extraction
    groups = {
        "one_value":[], 
        "recipient":[], 
        "pi":[], 
        "payment":[],
        "product":[], 
        "other_manufacture":[], 
    }

    for col in big_df.columns:
        n_of_unique_to_find = 1
        if big_df[col].nunique(dropna = False) == n_of_unique_to_find: # dropna=Flase i want column that fill with 1 value only not NA
            groups["one_value"].append(col)

        elif "Recipient" in col or "Hospital" in col or "Change_Type" in col:
            groups["recipient"].append(col)

        elif "Investigator" in col:
            groups["pi"].append(col)

        elif "Payment" in col or "payment" in col:
            groups["payment"].append(col)

        elif "Drug" in col or "Product" in col:
            groups["product"].append(col)

        else:
            groups["other_manufacture"].append(col)
            
    return groups

In [19]:
group_dict = large_df_to_smaller_groups(research_pay_clean)

total_col = 0

for k, v in group_dict.items():
    print(f"{k}: {len(v)}")
    total_col += len(v)
print("-"*20)
print(f"Total columns: {total_col}; Is it the same as original df: {total_col == research_pay_clean.shape[1]}")

one_value: 11
recipient: 6
pi: 30
payment: 7
product: 21
other_manufacture: 14
--------------------
Total columns: 89; Is it the same as original df: True

## 6 smaller groups

In [22]:
def apply_specific_fix(df):
    print(f"Update adress and add missing values")

    address_col = "Recipient_Primary_Business_Street_Address_Line1"
    drug_col = "Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1"
    ndc_col = "Associated_Drug_or_Biological_NDC_1"

    if address_col in df.columns:
        df[address_col] = df[address_col].replace(
            "12902 magnolia dr", 
            "12902 magnolia drive"
        )
    else: 
        print(f"--Warning: Column '{address_col}' does not exist. Skipping address fix.")

    if drug_col in df.columns and ndc_col in df.columns:
        mask = df[drug_col] == "imdelltra (amg757)"
        df.loc[mask, ndc_col] = "55513"
    else:
        missing = [c for c in [drug_col, ndc_col] if c not in df.columns]
        print(f"--Warning: Column(s) {missing} not found. Skipping NDC mapping.")
    
    print(f"Update adress and add missing values -- DONE")
    return df

def final_clean_func(df):
    # RECIPIENT INFO CLEAN
    print(f"Update cases and format in recipient info")
    col_w_value_to_capitalize = ["Recipient_State", "Change_Type"]
    col_w_value_to_title = group_dict["recipient"] + group_dict["one_value"]

    for col in col_w_value_to_title:
        if col not in df.columns:
            continue

        if df[col].dtype == "object":
            if col in col_w_value_to_capitalize:
                df[col] = df[col].str.upper()
            else:
                df[col] = df[col].str.title()
        else:
            print(f"--Skipped {col}, It is a {df[col].dtype}, not object.")
    print(f"Update cases and format in recipient info-- DONE")

    # PI INFO CLEAN
    print(f"Update cases and format in PI info")
    for col in group_dict["pi"]:
        if df[col].dtype == "object":
            if "State" in col:
                df[col] = df[col].str.upper()
            else:
                df[col] = df[col].str.title()
    print(f"Update cases and format in PI info-- DONE")

    # DATE FORMATTING CLEAN
    print(f"Update date type and formatting in payment info")
    df['Date_of_Payment'] = pd.to_datetime(
        df['Date_of_Payment'], 
        format="%m/%d/%Y"
    )

    # PAYMENT INFO CLEAN
    for col in group_dict["payment"]:
        if df[col].dtype == "object":
            if "State" in col:
                df[col] = df[col].str.upper()
            elif "Form_of_Payment_or_Transfer_of_Value" in col:
                df[col] = df[col].str.capitalize()
            else:
                df[col] = df[col].str.title()
    print(f"Update date type and formatting in payment info-- DONE")

    # PRODUCT INFO CLEAN
    print(f"Update formatting in product info")
    for col in group_dict["product"]:
        if df[col].dtype == "object":
            df[col] = df[col].str.title()

            col_to_upper = ["ClinicalTrials_Gov_Identifier"]
    print(f"Update formatting in product info-- DONE")

    # OTHER INFO CLEAN
    print(f"Update formatting in othe and manufacture info")
    for col in group_dict["other_manufacture"]:
        if df[col].dtype == "object":
            if col in col_to_upper:
                df[col] = df[col].str.upper()
            else:
                df[col] = df[col].str.title()
    print(f"Update formatting in other and manufacture info-- DONE")

    return df

In [23]:
research_pay_clean = (
    research_pay_clean
    .pipe(apply_specific_fix)
    .pipe(final_clean_func)
)
research_pay_clean

Update adress and add missing values
Update adress and add missing values -- DONE
Update cases and format in recipient info
--Skipped Teaching_Hospital_CCN, It is a int64, not object.
--Skipped Teaching_Hospital_ID, It is a int64, not object.
--Skipped Program_Year, It is a int64, not object.
Update cases and format in recipient info-- DONE
Update cases and format in PI info
Update cases and format in PI info-- DONE
Update date type and formatting in payment info
Update date type and formatting in payment info-- DONE
Update formatting in product info
Update formatting in product info-- DONE
Update formatting in othe and manufacture info
Update formatting in other and manufacture info-- DONE

C:\Users\delta\AppData\Local\Temp\ipykernel_27920\3210170165.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[address_col] = df[address_col].replace(
C:\Users\delta\AppData\Local\Temp\ipykernel_27920\3210170165.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].str.upper()
C:\Users\delta\AppData\Local\Temp\ipykernel_27920\3210170165.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].str.title()
C:\Users\delta\AppData\Local\Temp\ipykernel_27920\3210170165.py:52: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].str.title()
C:\Users\delta\AppData\Local\Temp\ipykernel_27920\3210170165.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].str.upper()
C:\Users\delta\AppData\Local\Temp\ipykernel_27920\3210170165.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Date_of_Payment'] = pd.to_datetime(
C:\Users\delta\AppData\Local\Temp\ipykernel_27920\3210170165.py:70: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].str.title()
C:\Users\delta\AppData\Local\Temp\ipykernel_27920\3210170165.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].str.upper()
C:\Users\delta\AppData\Local\Temp\ipykernel_27920\3210170165.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].str.capitalize()
C:\Users\delta\AppData\Local\Temp\ipykernel_27920\3210170165.py:77: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].str.title()
C:\Users\delta\AppData\Local\Temp\ipykernel_27920\3210170165.py:89: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].str.title()
C:\Users\delta\AppData\Local\Temp\ipykernel_27920\3210170165.py:87: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].str.upper()

,Change_Type,Covered_Recipient_Type,Teaching_Hospital_CCN,Teaching_Hospital_ID,Teaching_Hospital_Name,Recipient_Primary_Business_Street_Address_Line1,Recipient_Primary_Business_Street_Address_Line2,Recipient_City,Recipient_State,Recipient_Zip_Code,...,Preclinical_Research_Indicator,Delay_in_Publication_Indicator,Name_of_Study,Dispute_Status_for_Publication,Record_ID,Program_Year,Payment_Publication_Date,ClinicalTrials_Gov_Identifier,Research_Information_Link,Context_of_Research
0,NEW,Covered Recipient Teaching Hospital,100271,14408,Moffitt Cancer Center,12902 Magnolia Drive,NaN,Tampa,FL,33612,...,No,No,"Symphony-1: A Phase 1B/3 Double-Blind, Randomi...",No,1071108326,2024,06/30/2025,NCT04224493,NaN,NaN
1,NEW,Covered Recipient Teaching Hospital,100271,14408,Moffitt Cancer Center,12902 Magnolia Drive,NaN,Tampa,FL,33612,...,No,No,"Symphony-1: A Phase 1B/3 Double-Blind, Randomi...",No,1071108328,2024,06/30/2025,NCT04224493,NaN,NaN
2,NEW,Covered Recipient Teaching Hospital,100271,14408,Moffitt Cancer Center,12902 Magnolia Drive,NaN,Tampa,FL,33612,...,No,No,"Symphony-1: A Phase 1B/3 Double-Blind, Randomi...",No,1071104134,2024,06/30/2025,NCT04224493,NaN,NaN
3,NEW,Covered Recipient Teaching Hospital,100271,14408,Moffitt Cancer Center,12902 Magnolia Drive,NaN,Tampa,FL,33612,...,No,No,"Symphony-1: A Phase 1B/3 Double-Blind, Randomi...",No,1071104136,2024,06/30/2025,NCT04224493,NaN,NaN
4,NEW,Covered Recipient Teaching Hospital,100271,14408,Moffitt Cancer Center,12902 Magnolia Drive,NaN,Tampa,FL,33612,...,No,No,"Symphony-1: A Phase 1B/3 Double-Blind, Randomi...",No,1071108476,2024,06/30/2025,NCT04224493,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2298,NEW,Covered Recipient Teaching Hospital,100271,14408,Moffitt Cancer Center,12902 Magnolia Drive,NaN,Tampa,FL,33612,...,No,No,A Single Arm Phase 1B Study Of Hyper-Cvad Plus...,No,1153015173,2024,06/30/2025,NaN,NaN,NaN
2299,NEW,Covered Recipient Teaching Hospital,100271,14408,Moffitt Cancer Center,12902 Magnolia Drive,NaN,Tampa,FL,33612,...,No,No,A Single Arm Phase 1B Study Of Hyper-Cvad Plus...,No,1153015175,2024,06/30/2025,NaN,NaN,NaN
2300,NEW,Covered Recipient Teaching Hospital,100271,14408,Moffitt Cancer Center,12902 Magnolia Drive,NaN,Tampa,FL,33612,...,No,No,A Single Arm Phase 1B Study Of Hyper-Cvad Plus...,No,1153015177,2024,06/30/2025,NaN,NaN,NaN
2301,NEW,Covered Recipient Teaching Hospital,100271,14408,Moffitt Cancer Center,12902 Magnolia Drive,NaN,Tampa,FL,33612,...,No,No,A Single Arm Phase 1B Study Of Hyper-Cvad Plus...,No,1153015179,2024,06/30/2025,NaN,NaN,NaN
2302,NEW,Covered Recipient Teaching Hospital,100271,14408,Moffitt Cancer Center,12902 Magnolia Drive,NaN,Tampa,FL,33612,...,No,No,A Single Arm Phase 1B Study Of Hyper-Cvad Plus...,No,1153015181,2024,06/30/2025,NaN,NaN,NaN

# EXPORT CLEAN DATA

In [24]:
os.getcwd()

'd:\\A_Code_project\\Moffitt_payment_pj_PowerBI_Python'

In [25]:
output_folder_name = "clean_data_final"
output_dir = os.path.join(os.getcwd(), output_folder_name)
os.makedirs(output_dir, exist_ok=True)

print(f"Checking output directory: {output_dir}")

final_file_path = os.path.join(output_dir, "clean_moffitt_research_payment.csv")
research_pay_clean.to_csv(final_file_path, sep = ",")
print(f"Exported to [{final_file_path}]")

Checking output directory: d:\A_Code_project\Moffitt_payment_pj_PowerBI_Python\clean_data_final
Exported to [d:\A_Code_project\Moffitt_payment_pj_PowerBI_Python\clean_data_final\clean_moffitt_research_payment.csv]

# END